### ISSUE TITLE
Json serialization bug [counter tutorial]

### ISSUE THREAD

**Issue by romaingauthier** [ElrondNetwork/elrond-sdk-erdpy#31]
Querying the counter smart contract as described in the tutorial ([here](https://docs.elrond.com/developers/tutorials/counter/#interact-with-the-deployed-contract)):

```
erdpy contract query $CONTRACT_ADDRESS --function="get" --proxy="https://testnet-gateway.elrond.com"
```

yields 

```
[
    Traceback (most recent call last):
  File "/<HOME>/anaconda3/envs/elrond/bin/erdpy", line 8, in <module>
    sys.exit(main())
  File "/<HOME>/anaconda3/envs/elrond/lib/python3.8/site-packages/erdpy/cli.py", line 32, in main
    _do_main()
  File "/<HOME>/anaconda3/envs/elrond/lib/python3.8/site-packages/erdpy/cli.py", line 56, in _do_main
    args.func(args)
  File "/<HOME>/anaconda3/envs/elrond/lib/python3.8/site-packages/erdpy/cli_contracts.py", line 307, in query
    utils.dump_out_json(result)
  File "/<HOME>/anaconda3/envs/elrond/lib/python3.8/site-packages/erdpy/utils.py", line 139, in dump_out_json
    json.dump(data, outfile, indent=4, cls=ObjectEncoder)
  File "/<HOME>/anaconda3/envs/elrond/lib/python3.8/json/__init__.py", line 179, in dump
    for chunk in iterable:
  File "/<HOME>/anaconda3/envs/elrond/lib/python3.8/json/encoder.py", line 429, in _iterencode
    yield from _iterencode_list(o, _current_indent_level)
  File "/<HOME>/anaconda3/envs/elrond/lib/python3.8/json/encoder.py", line 325, in _iterencode_list
    yield from chunks
  File "/<HOME>/anaconda3/envs/elrond/lib/python3.8/json/encoder.py", line 438, in _iterencode
    o = _default(o)
  File "/<HOME>/anaconda3/envs/elrond/lib/python3.8/site-packages/erdpy/utils.py", line 34, in default
    return json.JSONEncoder.default(self, obj)
  File "/<HOME>/anaconda3/envs/elrond/lib/python3.8/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type QueryResult is not JSON serializable

**Comment by MWFIAE** [comment]
I made a while pr 2 days ago for that :)
https://github.com/ElrondNetwork/elrond-sdk-erdpy/pull/33

**Comment by romaingauthier** [comment]
Great, thanks!
