### ISSUE TITLE
arwen-wasm-vm project renamed to wasm-vm, crash arwen dependency install of erdpy

### ISSUE THREAD

**Issue by HaiTranThanh** [ElrondNetwork/elrond-sdk-erdpy#53]
```
INFO:downloader:download_url.url: https://github.com/ElrondNetwork/arwen-wasm-vm/archive/v1.4.22.tar.gz
INFO:downloader:download_url.filename: /home/haitran/elrondsdk/arwentools.v1.4.22.tar.gz
Downloading...
|_,_,_,_,_,,_,_,_,_,_|
 
INFO:downloader:Download done.
INFO:myprocess:run_process: ['go', 'build'], in folder: /home/haitran/elrondsdk/arwentools/v1.4.22/arwen-wasm-vm-1.4.22/cmd/arwendebug
Traceback (most recent call last):
  File "/home/haitran/elrondsdk/erdpy", line 8, in <module>
    sys.exit(main())
  File "/home/haitran/elrondsdk/erdpy-venv/lib/python3.8/site-packages/erdpy/cli.py", line 32, in main
    _do_main()
  File "/home/haitran/elrondsdk/erdpy-venv/lib/python3.8/site-packages/erdpy/cli.py", line 58, in _do_main
    args.func(args)
  File "/home/haitran/elrondsdk/erdpy-venv/lib/python3.8/site-packages/erdpy/cli_deps.py", line 35, in install
    dependencies.install_module(name, tag, overwrite)
  File "/home/haitran/elrondsdk/erdpy-venv/lib/python3.8/site-packages/erdpy/dependencies/install.py", line 20, in install_module
    module.install(tag, overwrite)
  File "/home/haitran/elrondsdk/erdpy-venv/lib/python3.8/site-packages/erdpy/dependencies/modules.py", line 37, in install
    self._post_install(tag)
  File "/home/haitran/elrondsdk/erdpy-venv/lib/python3.8/site-packages/erdpy/dependencies/modules.py", line 158, in _post_install
    self.build_binary(tag, 'arwendebug')
  File "/home/haitran/elrondsdk/erdpy-venv/lib/python3.8/site-packages/erdpy/dependencies/modules.py", line 169, in build_binary
    myprocess.run_process(['go', 'build'], cwd=source_folder, env=golang_env)
  File "/home/haitran/elrondsdk/erdpy-venv/lib/python3.8/site-packages/erdpy/myprocess.py", line 19, in run_process
    output = subprocess.check_output(args, shell=False, universal_newlines=True, stderr=subprocess.STDOUT, env=env, cwd=cwd)
  File "/usr/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.8/subprocess.py", line 493, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1704, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: PosixPath('/home/haitran/elrondsdk/arwentools/v1.4.22/arwen-wasm-vm-1.4.22/cmd/arwendebug')
```

**Comment by camilbancioiu** [comment]
We released erdpy v1.0.21 which fixes this, thank you.
