### ISSUE TITLE
Erdpy contract test calls Github API and gets rate limit error

### ISSUE THREAD

**Issue by raress96** [ElrondNetwork/elrond-sdk-erdpy#83]
Erdpy version 1.0.21.

For some reason, the `erdpy contract test` calls the GitHub API, but the build command doesn't. Because of this, if running the test command too often, you get locked out from actually running it. Full stack trace:

```
Traceback (most recent call last):
  File "/home/rares/elrondsdk/erdpy", line 8, in <module>
    sys.exit(main())
  File "/home/rares/elrondsdk/erdpy-venv/lib/python3.9/site-packages/erdpy/cli.py", line 32, in main
    _do_main()
  File "/home/rares/elrondsdk/erdpy-venv/lib/python3.9/site-packages/erdpy/cli.py", line 58, in _do_main
    args.func(args)
  File "/home/rares/elrondsdk/erdpy-venv/lib/python3.9/site-packages/erdpy/cli_contracts.py", line 171, in run_tests
    projects.run_tests(args)
  File "/home/rares/elrondsdk/erdpy-venv/lib/python3.9/site-packages/erdpy/projects/core.py", line 61, in run_tests
    dependencies.install_module("vmtools")
  File "/home/rares/elrondsdk/erdpy-venv/lib/python3.9/site-packages/erdpy/dependencies/install.py", line 20, in install_module
    module.install(tag, overwrite)
  File "/home/rares/elrondsdk/erdpy-venv/lib/python3.9/site-packages/erdpy/dependencies/modules.py", line 26, in install
    tag = self.get_latest_release()
  File "/home/rares/elrondsdk/erdpy-venv/lib/python3.9/site-packages/erdpy/dependencies/modules.py", line 137, in get_latest_release
    tag = utils.query_latest_release_tag(org_repo)
  File "/home/rares/elrondsdk/erdpy-venv/lib/python3.9/site-packages/erdpy/utils.py", line 253, in query_latest_release_tag
    response.raise_for_status()
  File "/home/rares/elrondsdk/erdpy-venv/lib/python3.9/site-packages/requests/models.py", line 953, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: rate limit exceeded for url: https://api.github.com/repos/ElrondNetwork/wasm-vm/releases/latest
```

Why the Github API is called on the contract test command is beyond me...

**Comment by andreibancioiu** [comment]
Hello @raress96, and thank you for reporting this :pray: 

`erdpy contract test` actually checks for the latest `vmtools` (dependency of erdpy) - and issues a Github API request while doing so, while `erdpy contract build` does not (at least, not as of February 2022).

The issue has been handled in PR https://github.com/ElrondNetwork/elrond-sdk-erdpy/pull/90 (not yet included in a release).

However, you can generate a personal access token in GitHub, then register it in `erdpy` like this:

```
erdpy config set github_api_token "YOUR-TOKEN"
```

Configuring the `github_api_token` will resolve the rate limit errors.
