### ISSUE TITLE
Error when getting list of transactions, if a faucet transaction with data=null is present

### ISSUE THREAD

**Issue by davideorsi** [ElrondNetwork/elrond-sdk-erdpy#84]
I was testing erdpy on a testnet account, and I noticed this error when trying to get the list of a user's transactions.

The faucet transactions have NULL data, and this causes the error below.
 
 ```
erdpy account get-transactions --address erd13kyvqzsp5cy4l4effhpem4tq3c8fqc3x764ccg7vp3mlng6p73eqjstf6w --proxy https://testnet-gateway.elrond.com

Traceback (most recent call last):
  File "/home/davideorsi/elrondsdk/erdpy-venv/bin/erdpy", line 8, in <module>
    sys.exit(main())
  File "/home/davideorsi/elrondsdk/erdpy-venv/lib/python3.8/site-packages/erdpy/cli.py", line 32, in main
    _do_main()
  File "/home/davideorsi/elrondsdk/erdpy-venv/lib/python3.8/site-packages/erdpy/cli.py", line 58, in _do_main
    args.func(args)
  File "/home/davideorsi/elrondsdk/erdpy-venv/lib/python3.8/site-packages/erdpy/cli_accounts.py", line 62, in get_account_transactions
    response = proxy.get_account_transactions(Address(address))
  File "/home/davideorsi/elrondsdk/erdpy-venv/lib/python3.8/site-packages/erdpy/proxy/core.py", line 46, in get_account_transactions
    data = (data[:TRUNCATE_DATA_THRESHOLD] + ' ... truncated ...') if len(data) > TRUNCATE_DATA_THRESHOLD else data
TypeError: object of type 'NoneType' has no len()
```

**Comment by andreibancioiu** [comment]
@davideorsi, thanks for reporting the issue :pray: 

It will be fixed by https://github.com/ElrondNetwork/elrond-sdk-erdpy/pull/96.
